### ISSUE TITLE
Changing beep frequency

### ISSUE THREAD

**Issue by ghost** [feross/beepbeep#11]
Is it possible to change the beep frequency and duration with nodejs? Some languages have something like: `Beep(hertz, milli)`  (https://stackoverflow.com/questions/38883092/how-to-make-motherboard-beep-through-c-code)
Or 
`SoundBeep, Frequency, Duration`
(AutoHotKey: https://www.autohotkey.com/docs/commands/SoundBeep.htm)

**Comment by ZRTSKY** [comment]
+

**Comment by zrtsky** [comment]
Im waiting too !

**Comment by feross** [comment]
Sorry, this module just prints the beep character to standard out. The sound is determined by your terminal and/or OS.
